"""name and created

Revision ID: 0cf38b3883fc
Revises: 5d6b27cf8c8b
Create Date: 2023-07-19 12:16:57.641309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf38b3883fc'
down_revision = '5d6b27cf8c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_commands_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('selected_commands_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('marker_commands_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('marker_commands_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('marker_commands_created')
        batch_op.drop_column('marker_commands_name')
        batch_op.drop_column('selected_commands_created')
        batch_op.drop_column('selected_commands_name')

    # ### end Alembic commands ###
