"""all default = 0

Revision ID: 302178a781f9
Revises: 7b53a775745d
Create Date: 2023-06-07 00:27:03.500444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302178a781f9'
down_revision = '7b53a775745d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meters_vertical', sa.Integer(), nullable=True))
        batch_op.alter_column('total_commands',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_commands',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('meters_vertical')

    # ### end Alembic commands ###
