"""trying

Revision ID: 5d6b27cf8c8b
Revises: 258221c0b3a8
Create Date: 2023-07-02 14:29:46.300194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6b27cf8c8b'
down_revision = '258221c0b3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_user', sa.Boolean(), nullable=True))
        batch_op.drop_column('new_or_old_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_or_old_user', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('old_user')

    # ### end Alembic commands ###
