"""wqdefrh

Revision ID: 7b53a775745d
Revises: 830313be4f30
Create Date: 2023-06-05 08:22:32.672370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b53a775745d'
down_revision = '830313be4f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_flights', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('attempted_flights')

    # ### end Alembic commands ###
