"""wdefrg

Revision ID: 830313be4f30
Revises: 119c0418a763
Create Date: 2023-06-05 08:04:26.029282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830313be4f30'
down_revision = '119c0418a763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flights', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crashes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_commands', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('meters_horizontal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('meters_horizontal')
        batch_op.drop_column('total_commands')
        batch_op.drop_column('crashes')
        batch_op.drop_column('flights')

    # ### end Alembic commands ###
